CREATE TABLE IF NOT EXISTS clients (
  id VARCHAR(64) PRIMARY KEY,
  name VARCHAR(255),
  phone VARCHAR(120),
  email VARCHAR(255),
  location VARCHAR(255),
  notes TEXT,
  geometry JSON,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS products (
  id VARCHAR(64) PRIMARY KEY,
  sku VARCHAR(120) UNIQUE,
  name VARCHAR(255),
  description TEXT,
  supplier VARCHAR(255),
  priceUsd DECIMAL(12,2),
  priceArs DECIMAL(12,2),
  stock INT,
  leadTime INT,
  components JSON,
  technicalInfo JSON,
  images JSON,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS components (
  id VARCHAR(64) PRIMARY KEY,
  sku VARCHAR(120) UNIQUE,
  name VARCHAR(255),
  description TEXT,
  supplier VARCHAR(255),
  priceUsd DECIMAL(12,2),
  priceArs DECIMAL(12,2),
  leadTime INT,
  stock INT,
  notes TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS budgets (
  id VARCHAR(64) PRIMARY KEY,
  clientId VARCHAR(64),
  clientName VARCHAR(255),
  items JSON,
  totalUsd DECIMAL(12,2),
  totalArs DECIMAL(12,2),
  totalWithIva DECIMAL(12,2),
  ivaPct DECIMAL(6,2),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

